---
all:
  children:
    switches:
      children:
        cisco:
          hosts:
            sw-cisco-3750:
              ansible_host: 10.10.10.251       # Switch Cisco Catalyst 3750 - à ajuster
              ansible_network_os: cisco.ios.ios
              ansible_connection: network_cli
              ansible_become: yes
              ansible_become_method: enable

        procurve:
          hosts:
            sw-procurve-1:
              ansible_host: 10.10.10.252       # ProCurve 2510-24 #1 - à ajuster
              ansible_network_os: community.network.procurve
              ansible_connection: network_cli

            sw-procurve-2:
              ansible_host: 10.10.10.253       # ProCurve 2510-24 #2 - à ajuster (si 2ème switch)
              ansible_network_os: community.network.procurve
              ansible_connection: network_cli
