---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/
  - storage/
  - apps/nginx/
  - apps/glpi/
  - apps/keycloak/
  - apps/gitlab/
  - apps/monitoring/prometheus/
  - apps/monitoring/grafana/
  - apps/monitoring/loki/
  - apps/uptime-kuma/
