---
# Credentials (à stocker dans ansible-vault en prod)
ansible_user: admin
ansible_password: "{{ vault_switch_password }}"
ansible_become_password: "{{ vault_enable_password }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# VLANs Atlas - conformes au plan d'adressage
vlans:
  - id: 10
    name: "Management"
  - id: 20
    name: "Core-Services"
  - id: 30
    name: "Applications"
  - id: 40
    name: "Data-BDD"
  - id: 50
    name: "Stockage-SAN"
  - id: 60
    name: "Corosync-HA"

# SNMP v2c
snmp_community_ro: "atlas_ro"
snmp_community_rw: "atlas_rw"
snmp_location: "Salle-Serveurs-Atlas"
snmp_contact: "admin@atlas.local"

# NTP
ntp_server_primary: "10.10.20.254"    # pfSense comme NTP relay
ntp_server_secondary: "0.fr.pool.ntp.org"

# Syslog (si tu déploies un syslog centralisé sur Zabbix/autre)
syslog_server: "10.10.20.50"
