---
# ── 1. Galera Cluster (BDD) ────────────────────
- name: Déployer le cluster Galera
  hosts: galera
  become: yes
  serial: 1
  roles:
    - galera

# ── 2. HashiCorp Vault ─────────────────────────
- name: Déployer Vault
  hosts: vault
  become: yes
  roles:
    - vault

# ── 3. K3s Masters ────────────────────────────
- name: Déployer K3s masters
  hosts: k3s_masters
  become: yes
  serial: 1
  roles:
    - k3s_master

# ── 4. K3s Workers ────────────────────────────
- name: Déployer K3s workers
  hosts: k3s_workers
  become: yes
  roles:
    - k3s_worker
